Repository martimolanes/TATASk_Manager, pull requests merged in 2024-04, with the labels that each got.

#5 Add Frontend View and Styles
  client/bun.lockb
  client/favicon.png
  client/index.html
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/components/LandingPage.tsx
  client/src/components/Navigation.tsx
  client/src/context/DataContext.tsx
  client/src/index.css
  client/src/routes/activities.tsx
  client/src/routes/dashboard.tsx
  client/src/routes/statistics.tsx
  client/src/routes/tasks.tsx
Labels: enhancement, frontend

#6 Add express API backend with Sequelize Integration
  database/init-db.sql
  database/postgres.yml
  server/.gitignore
  server/README.md
  server/bun.lockb
  server/index.ts
  server/package.json
  server/src/config/db.ts
  server/src/index.ts
  server/src/models/Activity.ts
  server/src/models/ActivityTag.ts
  server/src/models/ActivityType.ts
  server/src/models/Status.ts
  server/src/models/Tag.ts
  server/src/models/Task.ts
  server/src/models/TaskTag.ts
  server/src/models/index.ts
  server/src/routes/activity.ts
  server/src/routes/task.ts
Labels: enhancement, backend

#7 Frontend styling
  client/bun.lockb
  client/index.html
  client/package.json
  client/src/App.tsx
  client/src/components/LandingPage.tsx
  client/src/components/Navigation.tsx
  client/src/context/DataContext.tsx
  client/src/context/TabContext.tsx
  client/src/routes/activities.tsx
  client/src/routes/dashboard.tsx
  client/src/routes/tasks.tsx
Labels: enhancement, frontend

#8 Add CRUD operation to API setting default behaviours
  database/init-db.sql
  server/src/index.ts
  server/src/models/index.ts
  server/src/routes/activity.ts
  server/src/routes/tag.ts
  server/src/routes/task.ts
  server/test-api/Activity/activities-GET.bru
  server/test-api/Activity/activities-PUT.bru
  server/test-api/Activity/activity-DELETE.bru
  server/test-api/Activity/activity-POST.bru
  server/test-api/Tag/tag-get-all.bru
  server/test-api/Tag/tag-post.bru
  server/test-api/Task/task-DELETE.bru
  server/test-api/Task/task-UPDATE.bru
  server/test-api/Task/tasks-GET.bru
  server/test-api/Task/tasks-POST.bru
  server/test-api/bruno.json
  server/test-api/environments/environment.bru
Labels: enhancement, backend

#10 Documentation for the whole project
  README.md
  client/README.md
  database/README.md
  docs/client/application-components.md
  docs/client/application-context-data.md
  docs/client/application-routes.md
  docs/client/application-usage.md
  docs/database/database-schema.md
  docs/database/database-usage.md
  docs/server/server-usage.md
  server/README.md
Labels: documentation, help wanted, question
